language: python
python:
    - "2.7"
# command to install dependencies
install:
    - pip install requests
    - pip install coveralls
    - python setup.py install
# command to run tests
script:
    - coverage run -m unittest discover -v -s ./tests
after_success:
    - coverage report
    - coveralls
