language: python
python:
    - "2.7"
# command to install dependencies
install:
    - pip install requests
    - pip install coveralls
    - python setup.py install
# command to run tests
script:
    - coverage run ./tests/*.py -v
after_success:
    coveralls
