language: python
python:
    - "2.7"
install:
    - pip install coveralls
    - pip install pep8
    - python setup.py install
script:
    - nosetests --with-coverage
after_success:
    - pep8 modules/qs
    - coveralls
